language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
env:
  - PYMONGO_VERSION=3.7.1
  - PYMONGO_VERSION=3.0
  - PYMONGO_VERSION=2.0
services:
  - mongodb
# command to install dependencies
install:
  - pip install -q pymongo==$PYMONGO_VERSION
# command to run tests
script:
  - python -m unittest discover